apiVersion: batch/v1
kind: Job 
metadata:
  name: driver-experimental
  namespace: gleam
spec:
  template:
    spec:
      volumes:
      - name: gleam-data
        persistentVolumeClaim:
          claimName: gleam-pvc
          readOnly: true
      containers:
      - name: driver-container
        image: eiso/driver-experimental
        args: 
        - "driver"
        - "--query=test"
        - "--path=/data/siva/latest/00"
        - "--onDocker"
        - "--partitions=4"
        volumeMounts:
        - name: gleam-data
          mountPath: /data
          
      restartPolicy: Never