apiVersion: v1
kind: Pod 
metadata:
  name: driver-run
spec:
   containers:
   - name: driver-container
     image: eisokant/driver
     command: ["/usr/bin/driver"]
     args: ["--onDocker", "--query=test", "/data"]
